platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.12-alpine

params:
  GOPROXY: http://goproxy:8081

inputs:
  - name: repo
  - name: version

outputs:
  - name: server

run:
  path: ash
  args: [./repo/scripts/build-backend.sh]
