settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: server
    path: ./cmd/platform
    commands:
      run:
        status: true
    watcher:
      extensions:
        - go
      paths:
        - ../..
      ignore:
        paths:
          - .git
          - .realize
          - vendor
