gitea-repo-uri: git@git.ninjadojo.com.au:ninjadojo/boilerplate.git
gitea-repo-name: ninjadojo/boilerplate
gitea-private-key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKQIBAAKCAgEA03e9aoZmlZcgUoK5ytnmZnBkYE9DjmvokEKEVpC2VjBO8znJ
  LuZSfcukGVLHuxEs5BlI3PxUa9ELMZ3nTKuNdmJ9sMX6izeFhJ+U4fT8g2YzVHyn
  u/8uTxN1aR9/9+a4OMedOgk4BuqLLLqvQH0xyJaydCfyGLeZECQAcpfDUHRYkp1m
  SEDKRUgeU4GBwlCHTQVhVjSu5mjIAVEdtjBLLjyWDXQ5PuvjUXWxxUkqsJJkqlOo
  wouxBoc5cUQ6Tcv4DmiNe+ZuLesQFfaYbt9pOi+uV8pSJJlTd2/sS84KBjI4Qf2X
  0uUJMtyM+XzruX+f8Z+FTMcZXCZPUN1kiwswUtLTGDXEyPN9k+kIC8qAEyTONmig
  xkkMdCaOfAWOqJ46PUl5QbPhHNNMKitqZNDbkyjRm0dlrzSVdIztgrv+b55vQJ/0
  yeCuO7aXv6Yf0X41hhmzIk4pfe6xpTYZmNGEXfrGClfervGojGKy0zrhIjSMxLtZ
  wkRlgGBQ8kWQYUK9CDAt7K0nFNbOWJ/R4K+uyMumXL2v5bE42mIRLAabXrrZHvNk
  hS4+oDLzGXdYT+E3LL26A9aLiwe0cKe/cUKgKvs2mNCy8g4BLEe6WcopgjyPK7q5
  jU09CbFKb/u9/xMLwhjXvYZWX2SN4qng3Q8VJ8bH2NdY3HvNJQtVUUKiOaECAwEA
  AQKCAgEAnopRGkI1OsWY2ANmI60FzZtJxeLnNSm1rCIScYwBB9Ej/7o9GMpY4jMA
  jnO/hoIz87b5J6SN7l9FUyedN6AOaMkijpt/YUx475ts1ZMElcbTiO4EGzAPmf1u
  syeIm2UAjKErQU2UEataOGil52V1I3vHwsoH+Xv8Z1t2cnNRXUo89X7IJjdc7mBJ
  TDX2AKa7KYV1GlpZHilEeahE7Eh8tOd7YA7YtFHJlVL1uoFGXicDDae3CFQOnmRX
  LpIGXDklejfsiw2RYR+waab9VXJtw8/nl635s7K4Hv1sXNDWNxsDjoX/g39vTBCK
  KKn9WI9UbKQ6HfvPCYU3RdsV/CChUrlyO6VBrowFaY/KNpbWC2JE6Fk+qtpe3g02
  dAydmF2cxntTzh4Fy8YtUjjP9zb9cbNd/al7Pf8VVJoe2tdMQ6MQIeKyQhteEBSw
  1XiclIPkAwz1eW/TwDq0leapF8coEmIy7Tl1EniKtVstQDq2hY0157HFOkOmgMFV
  kuIKNm6hDGttLRD7k4c6wR5Ae0OmxZjZkR8PCFOk4m+4/H9Fnv5sXVCUwlLzfWdv
  0EtdQwJJZ6Rei6uGyoLrXV9olcjGEMa/vBXkkLCNc4r6cxcNW9YtGdHQDi5rkiRi
  Af+bRgiEg/IIvQDHZGpyd3/4FXvFX7tK5UVdQbEqN+G+XLmvBrkCggEBAPdHha+6
  5+SEvknNbYRpy86pg5kET2xQLIL6QjbrBSt4MKfFQO0OGCb6U1U2hdTOzVoDYtAZ
  AwcHiMIeoZ41PanfKluX7nkFs0oYkUievgsY+CWl3yIVyvvw3ThTLZAxbGnl+ioG
  NMwUTzK5iu3qr1QZQSCGY9506ieyfkBAfnFPW+gw+UV71sVUSBUsFo7mWLZhcxdN
  3kux23D7ricXO4Udw1zLATCWxXMAgOxHmACd8nKZbX/Yo+XLdTZ6tYw7kZ7kKcku
  NlxMoB01/Vzo1VxSjdS+lXmNJNFZSvr8SfQNKUtiMJ5xkL1VbY+es8SigSi9sK6o
  9lU/ONXnb7X6lbcCggEBANrs54awK5Ov/1mJt9nAnFhchI287xv1PxVWN6UC4Gbc
  vwJKAj8xFcNKiElTv0UivvJp+Fyo+DGUh394imgesLlYLRgQgy04KUqSx/ylQqw+
  io0a6UHpfuqZmNexhguAw87kIVRGWeBm2RFoRiok2Ypu10saql6O3y+tLRyDRFbI
  M16vnioh8y63GHdh2by8V/OC3NRYzK8e8mnEPfaDeCBM3ummiVaLGj9U6h55y+W+
  feHDyuuIPb+/8d9XG9hCpBw+aV98HMamUrSOpUy/skQHY5Sg12KtoT7/MHpYvm16
  jnkXZVzUk4nkh/jHk9yh4Qqg1YiYL9o8OHyhkG+n62cCggEAT6G/woytOuEoqnm2
  SAsN8BqU34UM0rOq8e8HvcnHm20UNiMGupBsZLj+dxWc2aBTbyZh/uPfHrdlaiYV
  I+6/UeIlMOPnjx+v0i/BMaK1TruWxgD5r29XM/UoOIhIxwOzhxLhkgD3pbTwoEQy
  IlYOakXLvF6q8Kuz8F7B240pavIEheyniaHM0zVGFVNiXFh/vxP4zUttR/EZ2vOh
  7MLFjyO7kzlow636HgPOgMi5gZFbz13rbl1kwo7Xy1iO+H8CcSnG7xurs+OVOHL3
  iaENfLK1LArH9iHm9mgMBnGSmz5Vywnu4EdwNhi5tKOF/s/aSjV0HXsaAO/gLLpg
  NjlhVwKCAQA9HGBMsqSXZ0uKPO07NY7vA3Rk9FZyoXToidaikzj8vaX8B5i09wiy
  KP3+Kgh8TgSrOnV/uBMAFAv2wzkvc1G1iy2bSBC18LVmAa8dkSwZVKPsW5S9N2ac
  KiAGJaHbWChQelHram/wOgVh3I+pd/vZrrMeXeUs3AjlEBxFl0beSqg8SB2IeU2e
  vrFvsbrL+m86pE7sX5VTVPoqGAOL6or/yTV4V2qC4/WBtDxeIXWPPit5d+QO90r1
  Wak0xOYa6g9RawKTCtwlf4wapq7xy5kBcGaVuIgnHXyjTyzDGj6d5NYcazF6RkSg
  +1ARW/SkY/Ojud2hcYn6C1FhSOA+qssFAoIBAQCockSZ3Qpm7BifDhZetu4aO85H
  RPEf/gSBu3+3VSL3wFH5e3uY1k7LuH9XLmdTAJEg/qfJduC4wZry01GsJy4tXVcV
  0FKr9jktMuQDgLgXrKzAf2l+Fv5DpOQjknElWUoOAieMZHAuWPzALBdi3gQFZaEO
  LQNSZK2po3tZJkpRXzQaTQcylMsvm4F2BJ4hpcpY4bnylcNJymDgPOSwDWu3KNuw
  520/PRqP3GtGexue0t36tJupQeBv05h2+Yk3UHi4f7Hc1/nVovkyOs/PjJXUk4lK
  m0IOk4vslbHCgelTz6qbfaPZzRNwstGBocsbw1/mTMRCCRYyxJsXkD/UJr1X
  -----END RSA PRIVATE KEY-----

initial-version: 0.0.1-dev.1
gitea-email: ci@mail.theninja.life
gitea-name: Concourse CI
s3_access_key_id: ninjaci
s3_secret_access_key: single-gauzy-oregonsilverspotbutterfly
